name: Shell command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: vypsat string
        run: echo "Spouštím GitHub Action step!"
      - name: Spuštění víceřádkového příkazu
        run: |
          node -v
          npm -v
          echo "Víceřádkový příkaz dokončen"
      - name: Příkaz přes Python cmd
        run: |
          import platform
          print(platform.processor())
          
          
          
          
          
          